# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-11 14:18
from __future__ import unicode_literals

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.models.UserManager()),
            ],
        ),
    ]
