# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraExpenses',
            fields=[
                ('extra_expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('extra_expenses', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('place_id_agm', models.CharField(max_length=255)),
                ('src_dest', models.CharField(choices=[('Source', 'Source'), ('Destination', 'Destination'), ('Return', 'Return')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('transporter', models.CharField(max_length=70)),
                ('primary_mobile', models.CharField(max_length=10, validators=[webapp.validators.MobileValidation(length=10, start_with='6-9')])),
                ('primary_person', models.CharField(blank=True, max_length=40, null=True)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('office_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('office_lng', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBody',
            fields=[
                ('vehicle_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=30)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
