# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_places_enquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='enquiry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='quotes.Enquiry'),
        ),
        migrations.AlterField(
            model_name='places',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
    ]
