# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_places_enquiry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place', to='masters.District'),
        ),
    ]
