# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_places_district_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('load_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('load_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('trans_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_id', models.ManyToManyField(related_name='trans_profile_dest', to='masters.District')),
                ('load_type', models.ManyToManyField(related_name='trans_profile_load_type', to='masters.LoadType')),
                ('source_id', models.ManyToManyField(related_name='trans_profile_source', to='masters.District')),
                ('transporter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trans_profile', to='masters.Transporter')),
                ('vehicle_type_id', models.ManyToManyField(related_name='trans_profile_veh_type', to='masters.VehicleType')),
            ],
        ),
    ]
