# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20190424_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id_agm',
            field=models.CharField(default='ChIJWf12_vy45zsRgwLF94V9Ns8', max_length=255),
        ),
    ]
