# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_places_place_id_agm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_id_agm',
            field=models.CharField(max_length=255),
        ),
    ]
