# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-16 12:11
from __future__ import unicode_literals

import webapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20190427_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='primary_mobile',
            field=models.CharField(max_length=10, validators=[webapp.validators.MobileValidation]),
        ),
    ]
