# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-16 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20190516_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='primary_mobile',
            field=models.CharField(max_length=10, validators=[webapp.validators.MobileValidation(length=10, start_with='6-9')]),
        ),
    ]
