# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20190516_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='office_lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='office_lng',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='office_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
