# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_auto_20190820_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=20, max_digits=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('load_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('load_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('trans_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_id', models.ManyToManyField(related_name='trans_profile_dest', to='masters.District')),
                ('load_type', models.ManyToManyField(related_name='trans_profile_load_type', to='masters.LoadType')),
                ('source_id', models.ManyToManyField(related_name='trans_profile_source', to='masters.District')),
                ('transporter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trans_profile', to='masters.Transporter')),
                ('vehicle_type_id', models.ManyToManyField(related_name='trans_profile_veh_type', to='masters.VehicleType')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place', to='masters.District'),
        ),
    ]
