# Generated by Django 2.2.5 on 2019-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_places_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='sublocality_level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
