# Generated by Django 2.2.5 on 2019-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_auto_20191114_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(choices=[('Trailer', 'Trailer'), ('Truck', 'Truck'), ('Tempo', 'Tempo'), ('Open Truck', 'Open Truck'), ('Container Truck', 'Container Truck'), ('Hydraulic Trailer', 'Hydraulic Trailer'), ('Misc', 'Misc')], default='Misc', max_length=30),
        ),
    ]
