# Generated by Django 2.2.5 on 2019-12-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_enquiry_load_type_new'),
        ('masters', '0016_vehicletype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterprofile',
            name='quote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_trans_profiles', to='quotes.SupplierQuote'),
        ),
    ]
