# Generated by Django 2.2.5 on 2020-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_transporterprofile_quote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtype',
            name='load_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
