# Generated by Django 2.2.5 on 2020-03-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_auto_20200205_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('client_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Client')),
            ],
        ),
    ]
