# Generated by Django 2.2.5 on 2022-02-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_client_clientaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
