# Generated by Django 2.0.5 on 2019-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_expenses',
            fields=[
                ('extra_expenses_id', models.AutoField(primary_key=True, serialize=False)),
                ('extra_expenses', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('transporter', models.CharField(max_length=70)),
                ('primary_mobile', models.PositiveIntegerField()),
                ('primary_person', models.CharField(blank=True, max_length=40, null=True)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_body',
            fields=[
                ('vehicle_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
