# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transporter_id', models.AutoField(primary_key=True, serialize=False)),
                ('transporter', models.CharField(max_length=70)),
                ('primary_mobile', models.PositiveIntegerField(default='123')),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_person', models.CharField(blank=True, max_length=40, null=True)),
                ('other_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_body',
            fields=[
                ('vehicle_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
