# Generated by Django 2.0.5 on 2019-02-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='enquiry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry'),
        ),
    ]
