# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_enquiry_new_sources'),
        ('masters', '0002_auto_20190204_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='enquiry_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry'),
        ),
    ]
