# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_places_enquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='enquiry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry'),
        ),
    ]
