# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20190205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
    ]
