# Generated by Django 2.0.5 on 2019-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20190208_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='src_dest',
            field=models.CharField(choices=[('Source', 'Source'), ('Destination', 'Destination'), ('Return', 'Return')], default='Source', max_length=20),
        ),
    ]
