# Generated by Django 2.0.5 on 2019-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_places_src_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='src_dest',
            field=models.CharField(choices=[('Source', 'Source'), ('Destination', 'Destination'), ('Return', 'Return')], max_length=20),
        ),
    ]
