# Generated by Django 2.2.5 on 2020-04-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import operations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_auto_20200402_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceipt',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lorryreceipt',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lorryreceipt',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(operations.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lorryreceiptno',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lorryreceiptno',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lorryreceiptno',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(operations.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lorryreceipt',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
