# Generated by Django 2.2.5 on 2020-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200406_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryreceipt',
            name='vehicle_no',
            field=models.CharField(default='MH04EY4991', max_length=12),
            preserve_default=False,
        ),
    ]
