# Generated by Django 2.2.5 on 2020-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20200406_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorryreceipt',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
