# Generated by Django 2.2.5 on 2020-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20200406_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='no_of_pkg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
