# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-04 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Floated Enquiry', 'Floated Enquiry'), ('Unfloated Enquiry', 'Unfloated Enquiry'), ('Confirmed Order', 'Confirmed Order')], default='Unfloated Enquiry', max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('load_type', models.CharField(choices=[('ODC', 'ODC'), ('Normal', 'Normal'), ('Part', 'Part'), ('Container', 'Container')], default='Normal', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('enquiry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('loading_date', models.DateTimeField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cnf_enquiry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cnf_loading_date', models.DateTimeField(blank=True, null=True)),
                ('cnf_comments', models.TextField(blank=True, null=True)),
                ('cnf_created', models.DateTimeField(blank=True, null=True)),
                ('extra_expenses', models.ManyToManyField(blank=True, to='masters.ExtraExpenses')),
                ('user', models.ForeignKey(on_delete=models.SET(quotes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('vehicle_body', models.ManyToManyField(blank=True, to='masters.VehicleBody')),
                ('vehicle_type', models.ManyToManyField(blank=True, to='masters.VehicleType')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('freight', models.PositiveIntegerField()),
                ('including_fine', models.CharField(max_length=20)),
                ('vehicle_avail', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enquiry_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry')),
                ('transporter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.Transporter')),
                ('user_id', models.ForeignKey(on_delete=models.SET(quotes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('vehicle_body_id', models.ManyToManyField(blank=True, to='masters.VehicleBody')),
                ('vehicle_type_id', models.ManyToManyField(to='masters.VehicleType')),
            ],
        ),
    ]
