# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-12 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190411_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierquote',
            name='including_fine',
        ),
        migrations.RemoveField(
            model_name='supplierquote',
            name='vehicle_avail',
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='vehicle_type',
            field=models.ManyToManyField(to='masters.VehicleBody'),
        ),
    ]
