# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20190512_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='including_fine',
            field=models.CharField(default='na', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='vehicle_avail',
            field=models.CharField(default='na', max_length=20),
            preserve_default=False,
        ),
    ]
