# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-12 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20190512_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierquote',
            old_name='rate',
            new_name='freight',
        ),
    ]
