# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-12 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20190427_1935'),
        ('quotes', '0006_auto_20190512_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierquote',
            old_name='enquiry',
            new_name='enquiry_id',
        ),
        migrations.RenameField(
            model_name='supplierquote',
            old_name='transporter',
            new_name='transporter_id',
        ),
        migrations.RenameField(
            model_name='supplierquote',
            old_name='vehicle_type',
            new_name='vehicle_body_id',
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='vehicle_type_id',
            field=models.ManyToManyField(to='masters.VehicleType'),
        ),
    ]
