# Generated by Django 2.0.5 on 2019-05-21 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20190512_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(quotes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='enquiry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='transporter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.Transporter'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(quotes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
