# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20190622_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry')),
            ],
        ),
    ]
