# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_confirmenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmenquiry',
            name='comments',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
