# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_confirmenquiry_enquiry_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmenquiry',
            name='loading_date',
            field=models.DateTimeField(),
        ),
    ]
