# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-09 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20190708_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmenquiry',
            name='enquiry_id',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='con_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='con_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='con_enquiry_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='con_loading_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='ConfirmEnquiry',
        ),
    ]
