# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-09 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_auto_20190809_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='con_comments',
            new_name='cnf_comments',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='con_created',
            new_name='cnf_created',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='con_enquiry_no',
            new_name='cnf_enquiry_no',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='con_loading_date',
            new_name='cnf_loading_date',
        ),
    ]
