# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-21 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_auto_20190921_1724'),
        ('quotes', '0017_auto_20190809_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='load_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.LoadType'),
        ),
    ]
