# Generated by Django 2.2.5 on 2019-12-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_transporterprofile_quote_id'),
        ('quotes', '0018_enquiry_load_type_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='freight_excl_org',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='freight_excl_rev',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='freight_incl_org',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='freight_incl_rev',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='freight_normal_org',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='freight_normal_rev',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupplierResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(choices=[('Pending', 'Pending'), ('Busy', 'Busy'), ('Awaiting Rates', 'Awaiting Rates')], default='Pending', max_length=20)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.Enquiry')),
                ('transporter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Transporter')),
            ],
        ),
    ]
