# Generated by Django 2.2.5 on 2019-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_auto_20191219_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('Searching', 'Searching'), ('Unloading', 'Unloading'), ('Not Available', 'Not Available'), ('Available', 'Available'), ('Status Unknown', 'Status Unknown'), ('No Response', 'No Response')], max_length=20, null=True),
        ),
    ]
