# Generated by Django 2.2.5 on 2020-01-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0020_supplierquote_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierquote',
            name='vehicle_status',
            field=models.CharField(blank=True, choices=[('searching', 'Searching'), ('unloading', 'Unloading'), ('not available', 'Not Available'), ('available', 'Available'), ('status unknown', 'Status Unknown')], max_length=20, null=True),
        ),
    ]
