# Generated by Django 2.2.5 on 2020-02-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_auto_20200104_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='load_type',
        ),
    ]
