# Generated by Django 2.2.5 on 2021-07-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20200204_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierquote',
            name='vehicle_status',
        ),
        migrations.AddField(
            model_name='supplierresponse',
            name='quote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response', to='quotes.SupplierQuote'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='vehicle_avail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplierresponse',
            name='response',
            field=models.CharField(choices=[('searching vehicle', 'Searching Vehicle'), ('vehicle unloading', 'Vehicle Unloading'), ('not available', 'Not Available'), ('available', 'Available'), ('status unknown', 'Status Unknown'), ('awaiting rates', 'Awaiting Rates'), ('not interested', 'Not Interested'), ('incorrect match', 'Incorrect Match')], max_length=20),
        ),
    ]
