# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-14 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Developer'), (2, 'Admin'), (3, 'Sales'), (4, 'Traffic Incharge'), (5, 'Accounts')], default=4),
        ),
    ]
