# Generated by Django 2.0.5 on 2019-02-03 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Floated Enquiry', 'Floated Enquiry'), ('Unfloated Enquiry', 'Unfloated Enquiry'), ('Confirmed Order', 'Confirmed Order')], default='Unfloated Enquiry', max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('return_location', models.CharField(blank=True, max_length=255, null=True)),
                ('load_type', models.CharField(choices=[('ODC', 'ODC'), ('Normal', 'Normal'), ('Part', 'Part'), ('Container', 'Container')], default='Normal', max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('enquiry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('loading_date', models.DateTimeField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('extra_expenses', models.ManyToManyField(blank=True, to='masters.Extra_expenses')),
                ('new_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.Places')),
                ('vehicle_body', models.ManyToManyField(blank=True, to='masters.Vehicle_body')),
                ('vehicle_type', models.ManyToManyField(blank=True, to='masters.Vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField()),
                ('including_fine', models.BooleanField()),
                ('vehicle_avail', models.BooleanField()),
                ('enquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Enquiry')),
                ('transporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.Transporter')),
                ('vehicle_type', models.ManyToManyField(to='masters.Vehicle_type')),
            ],
        ),
    ]
