# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QR', 'Quote Required'), ('FO', 'Finalised Order')], default='QR', max_length=2)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('return_location', models.CharField(blank=True, max_length=255, null=True)),
                ('load_type', models.CharField(choices=[('ODC', 'ODC'), ('FTL', 'Normal'), ('LTL', 'Part'), ('CON', 'Container')], default='FTL', max_length=3)),
                ('special_req', models.TextField(blank=True, null=True)),
                ('deal_number', models.PositiveIntegerField(blank=True, null=True)),
                ('loading_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_body', models.ManyToManyField(blank=True, to='masters.Vehicle_body')),
                ('vehicle_type', models.ManyToManyField(to='masters.Vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRetrieval',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.PositiveIntegerField()),
                ('including_fine', models.BooleanField()),
                ('vehicle_avail', models.BooleanField()),
                ('enquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Enquiry')),
                ('transporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.Transporter')),
                ('vehicle_type', models.ManyToManyField(to='masters.Vehicle_type')),
            ],
        ),
    ]
