# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EQ', 'Enquiry'), ('FO', 'Finalised Order')], default='EQ', max_length=2)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('return_location', models.CharField(max_length=255)),
                ('load_type', models.CharField(choices=[('ODC', 'ODC'), ('FTL', 'Normal'), ('LTL', 'Part'), ('CON', 'Container')], default='FTL', max_length=3)),
                ('special_req', models.TextField()),
                ('deal_number', models.PositiveIntegerField(blank=True, null=True)),
                ('loading_date', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicle_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_body')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_type')),
            ],
        ),
    ]
