# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-10 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='return_location',
        ),
    ]
