# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-04 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='new_source',
            new_name='new_sources',
        ),
    ]
