# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-05 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20190204_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='new_sources',
        ),
    ]
