# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-08 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_enquiry_new_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='source',
        ),
    ]
