# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-08 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_enquiry_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='destination',
            new_name='destinations',
        ),
    ]
