# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-08 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20190209_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='destinations',
        ),
    ]
