# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-12 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20190512_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierquote',
            old_name='user',
            new_name='user_id',
        ),
    ]
